homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret hass_trusted_network_1
  name: "Koti"
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  unit_system: metric
  temperature_unit: C
  country: FI
  currency: EUR
  time_zone: "Europe/Helsinki"
  internal_url: !secret hass_internal_url
  external_url: !secret hass_external_url
  customize: !include include/customizations.yaml
  allowlist_external_dirs:
    - /config

default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret hass_trusted_proxies_1
    - !secret hass_trusted_proxies_2

recorder:
  db_url: !secret postgresql_url
  purge_keep_days: 30

tts:
  - platform: google_translate

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    homeassistant.setup: error

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/weather-chart-card/weather-chart-card.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-text-input-row/lovelace-text-input-row.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/hass-sidebar-swipe/hass-sidebar-swipe.js
      type: module

    - url: /local/troinine/light-slider-card.js
      type: module
    - url: '/local/marked.min.js?v=4.2.12'
      type: module

    - url: /local/style.css
      type: css

  dashboards:
    lovelace-mobile:
      mode: yaml
      title: Mobiili
      show_in_sidebar: true
      filename: ui/mobile.yaml
    lovelace-tablet:
      mode: yaml
      title: Tabletti
      show_in_sidebar: true
      filename: ui/tablet.yaml

weather:
  - platform: template
    name: "Sää"
    unique_id: koti_custom
    condition_template: "{{ states('weather.koti') }}"
    temperature_template: "{{ states('sensor.netatmo_outdoor_temperature') | float }}"
    humidity_template: "{{ state_attr('weather.koti', 'humidity') | float }}"
    forecast_daily_template: "{{ state_attr('weather.koti', 'forecast') }}"
    pressure_template: "{{ state_attr('weather.koti', 'pressure') }}"
    wind_speed_template: "{{ state_attr('weather.koti', 'wind_speed') }}"
    wind_bearing_template: "{{ state_attr('weather.koti', 'wind_bearing') }}"
    ozone_template: "{{ state_attr('weather.koti', 'ozone') }}"
    visibility_template: "{{ state_attr('weather.koti', 'visibility') }}"

input_select:
  home_state:
    name: "Tila"
    icon: mdi:home
    options:
      - Kotona
      - Poissa
      - Nukkumassa
    initial: Kotona
  sauna_state:
    name: "Saunan tila"
    icon: mdi:shower
    options:
      - Pois
      - Lämpenee
      - Lämmin
      - Jäähtyy
    initial: Pois

input_boolean:
  !include include/booleans.yaml

input_number:
  !include include/numbers.yaml

input_text:
  !include include/texts.yaml

input_datetime:
  !include include/datetimes.yaml

sensor:
  !include_dir_merge_list sensors/generic

binary_sensor:
  !include sensors/binary-sensors.yaml

template:
  !include sensors/template.yaml

automation:
  !include include/automations.yaml

timer:
  !include include/timers.yaml

script:
  !include include/scripts.yaml

scene:
  !include include/scenes.yaml

switch:
  !include include/switches.yaml

light:
  !include include/lights.yaml

rest_command:
  !include include/rest_commands.yaml

camera:
  !include include/cameras.yaml

mqtt:
  !include sensors/mqtt.yaml

notify:
  !include include/notifications.yaml

utility_meter:
  !include include/utility-meters.yaml

group:
  !include include/groups.yaml

counter:
  !include include/counters.yaml
