---
button_card_templates: !include_dir_merge_named button_card_templates/
views:
  - title: "Mobiili"
    path: home
    icon: mdi:home
    cards:

      ### Navigation bar ###
      
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              display: flex;
              justify-content: center;
            }
        card:
          type: horizontal-stack
          cards:
            - type: custom:state-switch
              entity: sensor.radon_warning
              states:
                Nousussa:
                  type: 'custom:button-card'
                  template: chip_mdi_icon_only
                  styles:
                    icon:
                      - color: yellow # "var(--color-yellow)"
                  variables:
                    ulm_chip_mdi_icon_only_icon: mdi:radioactive
                  tap_action:
                    action: navigate
                    navigation_path: '/lovelace-mobile/radon'        
                Korkea:
                  type: 'custom:button-card'
                  template: chip_mdi_icon_only
                  styles:
                    icon:
                      - color: red
                  variables:
                    ulm_chip_mdi_icon_only_icon: mdi:radioactive
                  tap_action:
                    action: navigate
                    navigation_path: '/lovelace-mobile/radon'   
            - type: custom:state-switch
              entity: binary_sensor.doors
              states:
                "on":
                  type: 'custom:button-card'
                  template: chip_mdi_icon_only
                  variables:
                    ulm_chip_mdi_icon_only_icon: mdi:door-open
                  styles:
                    icon:
                      - color: yellow
            - type: conditional
              conditions:
                - entity: input_select.sauna_state
                  state_not: 'Pois'
              card:
                type: 'custom:button-card'
                template: chip_mdi_icon_only
                tap_action:
                  !include popups/sauna.yaml
                styles:
                  icon:
                    - color: |
                        [[[
                          var state = states['input_select.sauna_state'].state

                          if (state == 'Lämpenee') {
                            return 'yellow';
                          } else if (state == 'Lämmin') {
                            return 'red';
                          } else if (state == 'Jäähtyy') {
                            return '#00ccf5'
                          }
                        ]]]
                variables:
                  ulm_chip_mdi_icon_only_icon: mdi:shower
            - type: conditional
              conditions:
                - entity: sensor.co2_state
                  state_not: 'Alhainen'
              card:
                type: 'custom:button-card'
                template: chip_mdi_icon_only
                styles:
                  icon:
                    - color: 'yellow'
                variables:
                  ulm_chip_mdi_icon_only_icon: "[[[ return states['sensor.co2_state'].attributes.icon ]]]"
            - type: conditional
              conditions:
                - entity: sensor.humidity_state
                  state_not: 'Normaali'
              card:
                type: 'custom:button-card'
                template: chip_mdi_icon_only
                styles:
                  icon:
                    - color: |
                        [[[
                          var humidity_state = states['sensor.humidity_state'].state;
                          if (humidity_state == 'Alhainen') {
                            return '#00ccf5';
                          } else if (humidity_state == 'Korkea') {
                            return 'lightblue';
                          }
                        ]]]
                variables:
                  ulm_chip_mdi_icon_only_icon: "[[[ return states['sensor.humidity_state'].attributes.icon ]]]"
            - type: conditional
              conditions:
                - entity: input_boolean.on_vacation
                  state: 'on'
              card:
                type: 'custom:button-card'
                template: chip_mdi_icon_only
                styles:
                    icon:
                      - color: 'green'
                variables:
                  ulm_chip_mdi_icon_only_icon: mdi:palm-tree

      - type: vertical-stack
        cards:

          ### Koti ###
        
          - type: custom:button-card
            template: title
            name: |
              [[[
                let time = states['sensor.time'].state;
                let welcome = '';

                if (time > '18:00'){
                  welcome = "Iltaa";
                } else if (time > '12:00'){
                  welcome = "Päivää";
                } else if (time > '05:00'){
                  welcome = "Huomenta";
                } else {
                  welcome = "Hei";
                }

                return welcome + ', ' + user.name + '!';
              ]]]
          - type: weather-forecast
            style: |
              ha-card {
                border-radius: 20px;
              }
              ha-card.type-weather-forecast {
                padding: 5px 16px 5px 16px;
              }
              div.state {
                font-size: 20px;
              }
              div.temp {
                font-size: 20px !important;
              }
              span {
                font-size: 20px !important;
              }
            entity: weather.koti_custom
            show_forecast: false

          ### Primary states ###

          - type: custom:button-card
            template: title
            label: Koti
          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template: vertical_binary_button
                entity: input_select.home_state
                name: Tila
                icon: mdi:home
                label: "[[[ return entity.state ]]]"
                tap_action:
                  !include popups/home-state.yaml
              - type: 'custom:button-card'
                template: vertical_binary_button
                name: Autotalli
                variables:
                  - ulm_card_binary_sensor_alert: true
                entity: binary_sensor.mqtt_garage_door
                show_last_changed: true
                tap_action:
                  !include popups/garage.yaml
              - type: 'custom:button-card'
                template: vertical_binary_button
                variables:
                  - ulm_card_binary_sensor_alert: true
                entity: lock.ulko_ovi
                show_last_changed: true
          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template: vertical_binary_button
                entity: light.koti
                name: Valot
                label: |
                  [[[ 
                    if (entity.state == 'on') {
                      return 'Päällä'
                    } else {
                      return 'Pois'
                    }
                  ]]]
                tap_action:
                  !include popups/lighting.yaml
                styles:
                  icon:
                    - color: |
                        [[[
                          var color = entity.attributes.rgb_color;
                          if (color){
                            return 'rgb(' + entity.attributes.rgb_color + ')';
                          } else {
                            return 'var(--card-background-color)'
                          }
                        ]]]
              - type: 'custom:button-card'
                template: vertical_binary_button
                entity: sensor.air_quality
                name: Ilmanlaatu
                label: "[[[ return entity.state ]]]"
                tap_action:
                  !include popups/air-quality.yaml
                styles:
                  icon:
                    - color: |
                        [[[
                          if (entity.state == 'Radon nousussa' || entity.state == 'CO2 korkealla') {
                            return 'yellow';
                          } else if (entity.state == 'Radon korkealla') {
                            return 'red';
                          } else if (entity.state == 'Matala ilmankosteus') {
                            return '#00ccf5';
                          } else if (entity.state == 'Korkea ilmankosteus') {
                            return 'lightblue';
                          } else {
                            return 'green';
                          }
                        ]]]
              - type: 'custom:button-card'
                template: vertical_binary_button
                entity: sensor.nibe_heat_pump_state
                name: Maalämpö
                label: "[[[ return entity.state ]]]"
                icon: "[[[ return entity.attributes.icon ]]]"
                styles:
                  icon:
                    - color: |
                        [[[
                          var color = 'var(--custom-icon-color)'
                          if (entity.state == 'Lämmitys') {
                            color = 'red';
                          } else if (entity.state == 'Joutilas') {
                            color = 'rgba(var(--color-theme),0.2)' // minimalist default
                          }

                          return color;
                        ]]]
                tap_action:
                  !include popups/heating.yaml

          ### Quick info cards ###

          - type: custom:button-card
            template: title
            label: Ulko

          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: card_temperature
                entity: sensor.netatmo_koti_olohuone_ulko_temperature
                name: Lämpö
              - type: custom:button-card
                template: card_generic_icon_small
                entity: sensor.netatmo_koti_olohuone_ulko_humidity
                name: Kosteus
                styles:
                  icon:
                    - color: "#2565AE"
              - type: custom:button-card
                template: card_generic_icon_small
                entity: sensor.netatmo_koti_olohuone_pressure
                label: "[[[ return entity.state ]]]"
                name: Paine
                styles:
                  icon:
                    - color: "green"
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: card_generic_icon_small
                entity: sensor.netatmo_koti_olohuone_sade_rain_today
                name: Sade
                styles:
                  icon:
                    - color: dodgerblue
              - type: custom:button-card
                template: card_generic_icon_small
                entity: sensor.netatmo_koti_olohuone_sade_rain
                name: Ennuste
                styles:
                  icon:
              - type: custom:button-card
                template: card_generic_icon_small
                entity: sensor.netatmo_koti_olohuone_ulko_battery_percent
                name: Akku
                styles:
                  icon:
                    - color: dodgerblue

          ### Users ###

          - type: custom:button-card
            template: title
            label: Käyttäjät
          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template: card_person
                variables:
                  ulm_card_person_entity: person.tero
                  ulm_card_person_use_entity_picture: true    
              - type: 'custom:button-card'
                template: card_person
                variables:
                  ulm_card_person_entity: person.pia
                  ulm_card_person_use_entity_picture: true


  - title: Radon
    path: radon
    cards:
        ### Navigation bar ###

      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: chip_back
            tap_action:
              action: navigate
              navigation_path: '/lovelace-mobile/main'
      - type: vertical-stack
        cards:
          - type: custom:button-card
            template: title
            name: Radon
            label: Pitkäaikainen
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: card_radon
                entity: sensor.mqtt_airthings_waveplus_living_room_radon_long_term
                name: Olohuone
              - type: custom:button-card
                template: card_radon
                entity: sensor.mqtt_airthings_waveplus_sisu_radon_long_term
                name: Sisun huone
          - type: custom:button-card
            template: title
            label: Lyhytaikainen
          - type: custom:mini-graph-card
            style: |
              ha-card {
                border-radius: 20px
              }
            name: Olohuone
            icon: mdi:radioactive
            entities:
              - entity: sensor.mqtt_airthings_waveplus_living_room_radon_short_term
            show:
              name: true
              extrema: true
            color_thresholds:
              - value: 150
                color: red
              - value: 100
                color: yellow
              - value: 80
                color: green
            points_per_hour: 0.5
            hour24: true
            line_width: 3
            hours_to_show: 240
          - type: custom:mini-graph-card
            style: |
              ha-card {
                border-radius: 20px
              }
            name: Sisun huone
            icon: mdi:radioactive
            entities:
              - entity: sensor.mqtt_airthings_waveplus_sisu_radon_short_term
            show:
              name: true
              extrema: true
            color_thresholds:
              - value: 150
                color: red
              - value: 100
                color: yellow
              - value: 80
                color: green
            points_per_hour: 0.5
            hour24: true
            line_width: 3
            hours_to_show: 240


