base:
  variables:
    is_active: |
      [[[ return ['on', 'open'].indexOf(entity === undefined || entity.state) !== -1; ]]]
  template:
    - language_variables

base_card:
  variables:
    state_colors: false
    card_glow: false
  aspect_ratio: 1/1
  template:
    - base
  styles:
    name:
      - font-size: 1rem
      - font-weight: 500
    label:
      - font-size: 0.8rem
    state:
      - font-size: 0.9rem
      - font-weight: 500
    custom_fields:
      state2:
        - font-size: 0.9rem

    card:
      - border-radius: var(--border-radius)
      - padding: var(--button-card-padding)
      - '-webkit-box-shadow': |
          [[[
            if (!variables.card_glow) {
              return 'var(--box-shadow)'
            }

            var state = entity.state
            if (variables.state_colors) {
              var color = variables.state_colors[state]
              if (color) {
                return '0 0 0.95rem 0.2rem ' + color
              }
            }

            if (variables.icon_color) {
              return '0 0 0.95rem 0.2rem ' + variables.icon_color
            }

            return 'var(--box-shadow)'
          ]]]
      - box-shadow: |
          [[[
            if (!variables.card_glow) {
              return 'var(--box-shadow)'
            }

            var state = entity.state
            if (variables.state_colors) {
              var color = variables.state_colors[state]
              if (color) {
                return '0 0 0.95rem 0.2rem ' + color
              }
            }

            if (variables.icon_color) {
              return '0 0 0.95rem 0.2rem ' + variables.icon_color
            }

            return 'var(--box-shadow)'
          ]]]
      - transition: |
          [[[
            if (!variables.card_glow) {
              return 'none'
            } else {
              return 'all 2s ease'
            }
          ]]]

# Cannot inherit base_card
compact_card:
  aspect_ratio: null
  styles:
    card:
      - height: var(--button-card-compact-height)

wide_card:
  aspect_ratio: 2/1

base_icon:
  template:
    - base
  variables:
    icon_glow: false
    state_colors: false
    icon_color: false
  show_icon: true
  styles:
    icon:
      - width: 1.6rem
      - color: |
          [[[
            var state = entity.state
            if (variables.state_colors) {
              var color = variables.state_colors[state]
              if (color) {
                return color
              }
            }

            if (variables.icon_color) {
              return variables.icon_color
            }

            return 'var(--custom-icon-color-not-active)'
          ]]]
      - transition: all 2s ease
    img_cell:
      - background-color: "rgba(var(--color-theme-rgb),0.05)"
      - border-radius: "50%"
      - justify-self: start
      - '-webkit-box-shadow': |
          [[[
            if (!variables.icon_glow) {
              return 'none'
            }

            var state = entity.state
            if (variables.state_colors) {
              var color = variables.state_colors[state]
              if (color) {
                return '0 0 0.95rem 0.2rem ' + color
              }
            }

            if (variables.icon_color) {
              return '0 0 0.95rem 0.2rem ' + variables.icon_color
            }

            return 'none'
          ]]]
      - box-shadow: |
          [[[
            if (!variables.icon_glow) {
              return 'none'
            }

            var state = entity.state
            if (variables.state_colors) {
              var color = variables.state_colors[state]
              if (color) {
                return '0 0 0.95rem 0.2rem ' + color
              }
            }

            if (variables.icon_color) {
              return '0 0 0.95rem 0.2rem ' + variables.icon_color
            }

            return 'none'
          ]]]
      - transition: all 2s ease

base_icon_name:
  show_icon: true
  show_name: true
  show_label: false
  show_state: false
  template:
    - base_icon
  styles:
    img_cell:
      - background-color: rgba(var(--color-theme-rgb),0.05)
      - border-radius: 50%
      - width: 3rem
      - height: 3rem
      - place-self: center
    name:
      - justify-self: start
      - align-self: center
