---
- platform: xiaomi_cloud_map_extractor
  host: !secret vacuum_host
  token: !secret vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  name: vacuum_map
  country: de
  colors:
    color_robo: [224,224,224]
    color_charger: [27,117,27]
    color_path: [255, 255, 255]
    color_goto_path: [31, 113, 255]
    color_map_wall_v2: [69, 67, 70]
    color_obstacle: [30,30,30]
    color_virtual_walls: [255,0,0,60]
    color_no_go_zones_outline: [255,0,0]
    color_no_go_zones: [255,0,0,60]
    color_scan: [0,0,0,0]
    color_map_inside: [0,0,0,0]
    color_map_outside: [0,0,0,0]
    color_grey_wall: [0,0,0,0]
    color_map_wall: [0,0,0,0]
    color_zones_outline: [0,0,0,0]
    color_zones: [0,0,0,0]
    color_unknown: [0,0,0,0]
  room_colors:
    16: [69, 121, 180]  # Office
    17: [191, 90, 64]   # Kitchen
    18: [0, 126, 128]   # Entrance
    19: [61, 121, 181]  # Living room
    20: [192, 89, 64]   # Bedroom
    21: [0, 0, 0, 0]    # Not scanned room
    22: [70, 120, 182]  # Sisu
    23: [189, 124, 0]   # Otso
  draw:
    - charger
    - cleaned_area
    - ignored_obstacles
    - no_go_zones
    - obstacles
    - path
    - predicted_path
    - room_names
    - vacuum_position
    - virtual_walls
  map_transformation:
    scale: 2
    trim:
      bottom: 20
      left: 3
      right: 20
  sizes:
    charger_radius: 10
    vacuum_radius: 10
  texts:
    - text: Keittiö
      x: 30
      y: 40
      color: [224,224,224]
    - text: Olohuone
      x: 65
      y: 40
      color: [224,224,224]
    - text: Makuuhuone
      x: 75
      y: 13
      color: [224,224,224]
    - text: Eteinen
      x: 30
      y: 65
      color: [224,224,224]
    - text: Työhuone
      x: 25
      y: 83
      color: [224,224,224]
    - text: Otso
      x: 77
      y: 65
      color: [224,224,224]
    - text: Sisu
      x: 77
      y: 83
      color: [224,224,224]
  attributes:
    - calibration_points