---
button_card_templates:
  !include_dir_merge_named ../button_card_templates/
apexcharts_card_templates:
  !include templates/apexcharts/charts.yaml

views:
  - title: "Mobiili"
    path: home
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mod-card
            card_mod:
              style: |
                ha-card {
                  display: flex;
                  justify-content: center;
                }
            card:
              type: horizontal-stack
              cards:
                - type: custom:button-card
                  template: clock
                  entity: sensor.time
                  variables:
                    entity_weather: weather.koti_custom
                    entity_date: sensor.date
                    entity_temperature: sensor.netatmo_koti_olohuone_ulko_temperature

          - type: custom:button-card
            template: subtitle
            name: |
              [[[
                let time = states['sensor.time'].state;
                let welcome = '';

                if (time > '18:00'){
                  welcome = "Iltaa";
                } else if (time > '12:00'){
                  welcome = "Päivää";
                } else if (time > '05:00'){
                  welcome = "Huomenta";
                } else {
                  welcome = "Hei";
                }

                return welcome + ', ' + user.name + '!';
              ]]]

          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template:
                  - compact_info
                  - home_state
                tap_action:
                  !include ../popups/mobile/notifications.yaml
                double_tap_action:
                  !include ../popups/mobile/home.yaml

              - type: 'custom:button-card'
                template:
                  - compact_info
                  - front_door

              - type: 'custom:button-card'
                template:
                  - compact_info_extra
                  - garage_door
                tap_action:
                  !include ../popups/common/garage.yaml

          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template:
                  - compact_info_extra
                  - air_quality
                tap_action:
                  !include ../popups/mobile/air-quality.yaml
                variables:
                  extra_entity: "[[[ return entity.attributes.reporting_entity ]]]"
                  extra_text: |
                    [[[
                      var device_class = states[entity.attributes.reporting_entity].attributes.device_class
                      switch (device_class) {
                        case 'humidity':
                          return 'Kosteus'
                        case 'temperature':
                          return 'Lämpötila'
                        default:
                          return ''
                      }
                    ]]]

              - type: custom:button-card
                template:
                  - compact_info
                  - heat_pump_state
                tap_action:
                  !include ../popups/mobile/heating.yaml

              - type: custom:button-card
                template:
                  - compact_sensor_graph
                  - sensor_graph_thresholds_indoor_temperature
                entity: sensor.mqtt_airthings_waveplus_living_room_temperature
                variables:
                  name_override: Olohuone

          - type: custom:button-card
            template: subtitle
            name: Valaistus
            tap_action:
              !include ../popups/mobile/lights.yaml

          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template: compact_light_custom_actions
                entity: light.group_all_flat
                name: Valot
                tap_action:
                  !include ../popups/mobile/lights.yaml

              - type: 'custom:button-card'
                template: compact_light
                entity: light.group_living_room
                name: Olohuone

              - type: 'custom:button-card'
                template: compact_light
                entity: light.group_kitchen
                name: Keittiö

          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template: compact_light
                entity: light.group_kids_rooms
                name: Lapset

              - type: 'custom:button-card'
                template: compact_light
                entity: light.group_office
                name: Työhuone

              - type: 'custom:button-card'
                template: compact_light
                entity: light.group_bedroom
                name: Makkari

          - type: custom:button-card
            template: subtitle
            name: Perhe

          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template: compact_user
                entity: person.tero
                variables:
                  battery_charge_entity: sensor.tero_battery_level
                  battery_charging_status_entity: sensor.tero_battery_state

              - type: 'custom:button-card'
                template: compact_user
                entity: person.pia
                variables:
                  battery_charge_entity: sensor.pia_akun_varaustaso
                  battery_charging_status_entity: binary_sensor.pia_latautuu
