- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: rest
  name: 'Zen Quote'
  resource: https://zenquotes.io/api/random
  value_template: '{{ value_json[0].q }} - {{ value_json[0].a }}'
  scan_interval: 900

- platform: rest
  name: Todoist all tasks
  unique_id: todoist_all_tasks
  icon: mdi:list-status
  scan_interval: 300
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    project_id: !secret todoist_home_project_id
  headers:
    Authorization: !secret todoist_authorization_header
  value_template: "{{ iif(value_json, 'on', 'off') }}"
  json_attributes:
    - project
    - items

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
  scan_interval: 300
